// Generated by gencpp from file search_and_rescue/FrontierList.msg
// DO NOT EDIT!


#ifndef SEARCH_AND_RESCUE_MESSAGE_FRONTIERLIST_H
#define SEARCH_AND_RESCUE_MESSAGE_FRONTIERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <search_and_rescue/Frontier.h>

namespace search_and_rescue
{
template <class ContainerAllocator>
struct FrontierList_
{
  typedef FrontierList_<ContainerAllocator> Type;

  FrontierList_()
    : header()
    , frontiers()  {
    }
  FrontierList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frontiers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::search_and_rescue::Frontier_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::search_and_rescue::Frontier_<ContainerAllocator> >> _frontiers_type;
  _frontiers_type frontiers;





  typedef boost::shared_ptr< ::search_and_rescue::FrontierList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::search_and_rescue::FrontierList_<ContainerAllocator> const> ConstPtr;

}; // struct FrontierList_

typedef ::search_and_rescue::FrontierList_<std::allocator<void> > FrontierList;

typedef boost::shared_ptr< ::search_and_rescue::FrontierList > FrontierListPtr;
typedef boost::shared_ptr< ::search_and_rescue::FrontierList const> FrontierListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::search_and_rescue::FrontierList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::search_and_rescue::FrontierList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::search_and_rescue::FrontierList_<ContainerAllocator1> & lhs, const ::search_and_rescue::FrontierList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frontiers == rhs.frontiers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::search_and_rescue::FrontierList_<ContainerAllocator1> & lhs, const ::search_and_rescue::FrontierList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace search_and_rescue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::search_and_rescue::FrontierList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search_and_rescue::FrontierList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_and_rescue::FrontierList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_and_rescue::FrontierList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_and_rescue::FrontierList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_and_rescue::FrontierList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::search_and_rescue::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8bff21bf47ea8f3347bdb50aeb48771";
  }

  static const char* value(const ::search_and_rescue::FrontierList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8bff21bf47ea8f3ULL;
  static const uint64_t static_value2 = 0x347bdb50aeb48771ULL;
};

template<class ContainerAllocator>
struct DataType< ::search_and_rescue::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "search_and_rescue/FrontierList";
  }

  static const char* value(const ::search_and_rescue::FrontierList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::search_and_rescue::FrontierList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FrontierList.msg\n"
"\n"
"Header header # Standard ROS Header\n"
"Frontier[] frontiers # List of frontiers \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: search_and_rescue/Frontier\n"
"# Frontier.msg\n"
"\n"
"Cell[] cells # List of cells\n"
"================================================================================\n"
"MSG: search_and_rescue/Cell\n"
"# Cell.msg\n"
"\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::search_and_rescue::FrontierList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::search_and_rescue::FrontierList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frontiers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontierList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::search_and_rescue::FrontierList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::search_and_rescue::FrontierList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frontiers[]" << std::endl;
    for (size_t i = 0; i < v.frontiers.size(); ++i)
    {
      s << indent << "  frontiers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::search_and_rescue::Frontier_<ContainerAllocator> >::stream(s, indent + "    ", v.frontiers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEARCH_AND_RESCUE_MESSAGE_FRONTIERLIST_H
