// Generated by gencpp from file search_and_rescue/PointList.msg
// DO NOT EDIT!


#ifndef SEARCH_AND_RESCUE_MESSAGE_POINTLIST_H
#define SEARCH_AND_RESCUE_MESSAGE_POINTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace search_and_rescue
{
template <class ContainerAllocator>
struct PointList_
{
  typedef PointList_<ContainerAllocator> Type;

  PointList_()
    : points()  {
    }
  PointList_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::search_and_rescue::PointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::search_and_rescue::PointList_<ContainerAllocator> const> ConstPtr;

}; // struct PointList_

typedef ::search_and_rescue::PointList_<std::allocator<void> > PointList;

typedef boost::shared_ptr< ::search_and_rescue::PointList > PointListPtr;
typedef boost::shared_ptr< ::search_and_rescue::PointList const> PointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::search_and_rescue::PointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::search_and_rescue::PointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::search_and_rescue::PointList_<ContainerAllocator1> & lhs, const ::search_and_rescue::PointList_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::search_and_rescue::PointList_<ContainerAllocator1> & lhs, const ::search_and_rescue::PointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace search_and_rescue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::search_and_rescue::PointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search_and_rescue::PointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_and_rescue::PointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_and_rescue::PointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_and_rescue::PointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_and_rescue::PointList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::search_and_rescue::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::search_and_rescue::PointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::search_and_rescue::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "search_and_rescue/PointList";
  }

  static const char* value(const ::search_and_rescue::PointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::search_and_rescue::PointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PointList.msg\n"
"geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::search_and_rescue::PointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::search_and_rescue::PointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::search_and_rescue::PointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::search_and_rescue::PointList_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEARCH_AND_RESCUE_MESSAGE_POINTLIST_H
